import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./componants/Navbar";
import Footer from "./componants/Footer";
import SessionWrapper from "./componants/SessionWrapper";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 ..." >
      <SessionWrapper>
        <Navbar/>
        <div >
        {children}
        </div>
        <Footer/>
        </SessionWrapper>
        </body>
    </html>
  );
}
